#page title
page_title                                :  Walls - Wallpaper Sevice                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
# App Info
ios_app_id                                :                   # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.naveenjujaray.walls&hl=en_IN                                       # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/walls.png                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Walls                                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Gifted by the world’s most generous community of photographers.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Naveen Jujaray                               
your_link                                 : https://naveenjujaray.js.org                    
your_city                                 : Hyderabad, In                               
email_address                             : jujaraynaveen@gmail.com
facebook_username                         : naveenjujaray                                      
instagram_username                        : naveenjujaray
twitter_username                          : naveenjujaray
blog_url                                  : naveenjujaray.js.org
dev_username                              : naveenjujaray
medium_username                           : naveenjujaray
github_username                           : naveenjujaray
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 1.2 million + Photos
    description                           : From the world’s most generous community of photographers.
    fontawesome_icon_name                 : images
    
  - title                                 : New wallpapers everyweek
    description                           : We keep updating for you.
    fontawesome_icon_name                 : sync-alt

  - title                                 : Made with Flutter
    description                           : To the whole new community as a base.
    fontawesome_icon_name                 : terminal

  - title                                 : 50+ Categories
    description                           : Choose from different Categories of what you love.
    fontawesome_icon_name                 : star

  - title                                 : Want more ?
    description                           : All you need is to search for what you need in those million photos.
    fontawesome_icon_name                 : search
  
  - title                                 : Report an issue / Suggest a feature
    description                           : Take a screenshot and send us the issue you're facing using floating icon in the app.
    fontawesome_icon_name                 : life-ring

  - title                                 : Show some support
    description                           : by Buying a coffee for me through the app.
    fontawesome_icon_name                 : donate


  - title                                 : Ad-Free
    description                           : No ads at all and never will be so, feel free to enjoy it.
    fontawesome_icon_name                 : ad

  - title                                 : Open Source
    description                           : Source code is available on Github check it out.
    fontawesome_icon_name                 : book-reader

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown